# yaml-language-server: $schema=.schema.yaml
# See:
#   - https://github.com/bootc-dev/bootc/blob/75e1a40eb5aa06938b7da304aa6ed451adbfa064/.gemini/config.yaml
#   - https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github
have_fun: false
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true
ignore_patterns: []
